version: '3.7'

volumes:
  #  app_memcached: {}
  app_database: {}

networks:
  wetooo_network:
    name: wetooo_network
    driver: bridge

services:

  php_wetooo:
    build: php
    hostname: wetooo
    volumes:
      - ../:/var/www/app:delegated
      - ./data/shell_history:/home/utente/shell_history
    networks:
      - wetooo_network
    environment:
      - HISTFILE=/home/utente/shell_history/.x_history
      - APP_ENV=local

  web:
    image: nginx:1.23.0-alpine
    depends_on:
      - php_wetooo
    volumes:
      - ./nginx/host.conf:/etc/nginx/conf.d/default.conf
      - ../:/var/www/app:delegated
      - ./data/logs/nginx/:/var/log/nginx
    networks:
      - wetooo_network
    ports:
      - "8080:80"

  servicedb:
    image: mariadb:10.5.16
    volumes:
      - app_database:/var/lib/mysql
      - ./mariadb/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./data/db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=weto
    networks:
      - wetooo_network
    ports:
      - "3312:3306"
